# Generated by Django 5.1.6 on 2025-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.IntegerField()),
                ('service', models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('Custom Software Development', 'Custom Software Development'), ('Search Engine Development', 'Search Engine Development'), ('Mobile App Development', 'Mobile App Development'), ('Cloud & Hosting Services', 'Cloud & Hosting Services'), ('ChatBot & Automations', 'ChatBot & Automations'), ('Other', 'Other')], max_length=200, null=True)),
                ('Message', models.TextField(max_length=300)),
                ('contacted_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('small_description', models.TextField(max_length=100)),
                ('f_description', models.TextField(max_length=600)),
                ('l_description', models.TextField(max_length=600)),
                ('fimage', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('service', models.CharField(blank=True, choices=[('Web Design', 'Web Design'), ('Custom Software Development', 'Custom Software Development'), ('Search Engine Development', 'Search Engine Development'), ('Mobile App Development', 'Mobile App Development'), ('Cloud & Hosting Services', 'Cloud & Hosting Services'), ('ChatBot & Automations', 'ChatBot & Automations'), ('Other', 'Other')], max_length=200, null=True)),
                ('short_description', models.CharField(max_length=1000)),
                ('long_description', models.TextField(max_length=300)),
                ('solution', models.CharField(max_length=500)),
                ('stack_technology', models.CharField(max_length=200)),
                ('fimage', models.ImageField(upload_to='images/')),
                ('gimage1', models.ImageField(upload_to='images/')),
                ('gimage2', models.ImageField(upload_to='images/')),
                ('gimage3', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
